### ISSUE TITLE
Code release.

### ISSUE THREAD

**Issue by mohammed-amr** [bethgelab/robustness#1]
Hello! I'm interested in seeing your implementation of the paper. When do you plan on releasing the code? Thanks!

**Comment by tonmoy-saikia** [comment]
+1  for this. 

Here's my snippet.
```
def update_bn_params(model, val_loader, args):
    val_loader = torch.utils.data.DataLoader(val_loader.dataset,
                                             batch_size=val_loader.batch_size,
                                             shuffle=True, num_workers=val_loader.num_workers)
    def use_test_statistics(module):
        if isinstance(module, nn.BatchNorm2d):
            module.train()
    model = copy.deepcopy(model)
    model.eval()
    model.apply(use_test_statistics)
    print("Updating BN params (num updates:{})".format(args.num_bn_updates))
    with torch.no_grad():
        for i, (images, target) in enumerate(val_loader):
            if i<args.num_bn_updates:
                images = images.cuda(args.gpu, non_blocking=True)
                output = model(images)
    print("Done.")
    return model
```

**Comment by mohammed-amr** [comment]
Yeah, that's very similar to mine. I was just hoping to get an implementation straight from the authors for a baseline comparison. 

Thanks!

**Comment by stes** [comment]
Hi @mohammed-amr , sorry for the delay! We are planning to release soon.

Until then, I can confirm that @tonmoy-saikia 's implementation is the correct version for the standard evaluation setting without a prior on the statistics (`N -> ∞`, dash-dotted line below):

![image](https://user-images.githubusercontent.com/727984/110469192-a0dc9000-80d9-11eb-9acf-6b420ebfb988.png)

The release will include the `N < ∞` variant as long as an exponential moving averaging version interesting in deployment settings as well. If you need to benchmark the case including training stats priors, we can look into shipping a pre-release version for that in the coming days?

If you need to benchmark fully adapted models (i.e. using a virtual batch size of n = 50,000), we could also share model checkpoints adapted to all IN-C corruptions.

Please let us know if the case sketched by @tonmoy-saikia  above is already sufficient, or if you need additional code for other experiments (train stats priors, adapted models, etc.).

**Comment by stes** [comment]
@mohammed-amr we just updated the repo. Please let me know if you have any further questions!
