### ISSUE TITLE
Clould you release the sota model checkpoint Resnet-50 on ImageNet-C

### ISSUE THREAD

**Issue by double-fire-0** [bethgelab/robustness#5]
From here, https://paperswithcode.com/sota/unsupervised-domain-adaptation-on-imagenet-c
I notice that you have the sota model of ResNet-50 on ImageNet-c

![image](https://user-images.githubusercontent.com/69890917/140934070-3b67ba96-23fb-466e-8df2-62942d6564db.png)

Will you release the checkpoint of this model in the feature?

**Comment by stes** [comment]
Hi @double-fire-0 , thanks for asking! A full list to links of checkpoints used in the paper is available in [our paper](https://arxiv.org/pdf/2006.16971.pdf), in the Appendix E section (page 34-35).

For the checkpoint you asked about, please refer to https://github.com/hendrycks/imagenet-r#other-resources:
![image](https://user-images.githubusercontent.com/727984/140943243-602cf307-79aa-481f-a2a7-b4b599546b00.png)

Please feel free to re-open this issue if your question is not addressed by this. Thanks! :)
