### ISSUE TITLE
issues in test_datasets.py

### ISSUE THREAD

**Issue by MarcellusZhao** [bethgelab/robustness#6]
Hello, Schneider

I came across some questions during reproducing this work and need your help:
- When I set `cwd` as "/robustness", and run the following command `python examples/batchnorm/src/evaluate.py --imagenet-path imagenet/`, I came across a `ModuleNotFoundError: No module named robusta`. I add `/robusta` into `sys.path` to solve this problem. I guess it is maybe because forgetting to change the relative path after the movement of `evaluate.py` to `src`. Of course, maybe you are right and I don't know some specific implementation under this situation.

- I want to ask the difference between EMABatchNorm and PartlyAdaptiveBN when setting `adapt_mean` and `adapt_var` as `True`. I think they both use testing set statistics, but the momentum of `EMABatchNorm` is not zero, while the momentum of `PartlyAdaptiveBN` is zero.

Thanks in advance!

**Comment by stes** [comment]
@MarcellusZhao , thanks a lot for flagging, and sorry for the slow response. We fixed this through #12 now and updated the package.

**Comment by Aikoin** [comment]
hello! I noticed that in the EMABatchNorm method, the momentum is set to None. How can the test statistics be updated using moving averages in this case?
