### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by WeiHao97** [bethgelab/robustness#7]
Dear Authors,
Thanks for the wonderful repo. Could you take a look at this installation issue I encountered when running 'pip install --verbose git+git://github.com/bethgelab/robustness.git'?
'''
Fetching project page and analyzing links: https://pypi.ngc.nvidia.com/pip/
Getting page https://pypi.ngc.nvidia.com/pip/
Found index url https://pypi.ngc.nvidia.com
Starting new HTTPS connection (1): pypi.ngc.nvidia.com:443
https://pypi.ngc.nvidia.com:443 "GET /pip/ HTTP/1.1" 301 0
Starting new HTTPS connection (1): developer.download.nvidia.com:443
https://developer.download.nvidia.com:443 "GET /compute/redist/pip/ HTTP/1.1" 404 445
Could not fetch URL https://pypi.ngc.nvidia.com/pip/: 404 Client Error: Not Found for url: https://developer.download.nvidia.com/compute/redist/pip/ - skipping
Given no hashes to check 209 links for project 'pip': discarding no candidates
Removed build tracker: '/tmp/pip-req-tracker-b4ndlbqj'
'''
Thank you

**Comment by Djoels** [comment]
Hi, I assume it should be 
`pip install git+https://github.com/bethgelab/robustness.git`
instead?

**Comment by stes** [comment]
Hi @WeiHao97 , we haven't fully updated the pypi package yet. In the meantime, please use @Djoels suggestion and 

```
pip install git+https://github.com/bethgelab/robustness.git
```

Let me know if this works!

**Comment by stes** [comment]
Although there seems to another installation issue, see #9
