### ISSUE TITLE
import robusta

### ISSUE THREAD

**Issue by cuitaoyong** [bethgelab/robustness#9]
Dear Authors,
Thanks for the wonderful repo. 
After I use this command “pip install git+https://github.com/bethgelab/robustness.git” to install the package, I still can't import the package such as “import robusta”

**Comment by stes** [comment]
@cuitaoyong , thanks for flagging --- I can reproduce the error and will look into over the weekend, then report back here. Thanks for the patience, and thanks for your interest in using `robusta`!

**Comment by stes** [comment]
Hi @cuitaoyong , this is now addressed through #10 #11 and #12. The package is available on pypi:

https://pypi.org/project/robusta/

You can install via

```
pip install robusta
```

Could you give this a try, and re-open this issue, if it still does not work? Thanks for flagging!
